version: '3'
services:
  # Prometheus контейнер
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
    - my-network
    

  # Приложение
  app:
    image: spring-web-app:latest
    container_name: app
    ports:
      - "8080:8080"
    networks:
    - my-network

  grafana:
   image: grafana/grafana
   container_name: graf
   ports:
     - 3000:3000
   networks:
   - my-network


networks:
    my-network: